# Generated by Django 5.2.12 on 2026-03-05 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('farm_type', models.CharField(choices=[('vegetables', 'Vegetables'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('meat', 'Meat'), ('mixed', 'Mixed Produce')], max_length=20)),
                ('offers_delivery', models.BooleanField(default=False)),
                ('offers_pickup', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
