# Generated by Django 5.1 on 2026-03-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_season', 'In Season (Available)'), ('out_of_season', 'Out of Season (Unavailable)'), ('limited', 'Limited Stock')], default='in_season', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('dairy_eggs', 'Dairy & Eggs'), ('bakery', 'Bakery'), ('meat', 'Meat'), ('fruit', 'Fruit'), ('honey_preserves', 'Honey & Preserves'), ('drinks', 'Drinks'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
